### ISSUE TITLE
WARNING SYSTEM - voip chat/coms

### ISSUE THREAD

**Issue by l3v1ath3n** [Beefaloaf/NANA_Wasteland.Altis#10]
people are getting kicked for using proper coms practices. group, vehicle, direct. etc.

**Comment by l3v1ath3n** [comment]
i think we discussed, but we cannot give admin global chat privileges can we.

**Comment by Beefaloaf** [comment]
I havent found a way.  It's BattleEye Extended Controls that does the work here.  It has it's own admin list, but no way to tell it that they should be exempt from the chat rules.  It's dumb.
We can edit the number of warnings for each channel, and disable it per channel...
.
