### ISSUE TITLE
request for new mission types. 

### ISSUE THREAD

**Issue by l3v1ath3n** [Beefaloaf/NANA_Wasteland.Altis#12]
is that even possible?

**Comment by Beefaloaf** [comment]
It is...   we've gained a few new types with the latest update.  There's all coded missions made for easy  timer based repetition...

I'm currently dabbling with just modify the existing ones.

**Comment by l3v1ath3n** [comment]
very cool. We were thinking about a roaming infantry type. Perhaps even unmarked.

**Comment by Beefaloaf** [comment]
Those would be non missions random infantry

**Comment by Beefaloaf** [comment]
In due time, we'll have unique missions
