### ISSUE TITLE
Vehicle clipping into ground

### ISSUE THREAD

**Issue by Dredhawk** [Beefaloaf/NANA_Wasteland.Altis#15]
Sometimes when hopping into vehicles they will clip into the ground half way up the tires and wont move, I feel this is also the reason why choppers sometimes explode when you hop into them.

**Comment by Beefaloaf** [comment]
Perhaps you're a magician!

**Comment by l3v1ath3n** [comment]
i havent done it yet! not sure how they are doing it. its odd lol

**Comment by Beefaloaf** [comment]
1.38 bug.   Awaiting a fix from smarter people.
