### ISSUE TITLE
Screen Shudder

### ISSUE THREAD

**Issue by l3v1ath3n** [Beefaloaf/NANA_Wasteland.Altis#17]
heartbeat like camera shake. on foot and vehicle. Like trex is walking in the immediate area. every couple of seconds. Last time we did a restart it seemed to resolve.

**Comment by l3v1ath3n** [comment]
confirmed that reset resolves this. happens about every 3 hours.

**Comment by l3v1ath3n** [comment]
found this on the web.. appears to be no answer 

http://feedback.arma3.com/view.php?id=22400&nbn=4

**Comment by l3v1ath3n** [comment]
artemus mentioned that it may be at the same time that the money shipment objective freezes.

**Comment by l3v1ath3n** [comment]
http://forums.a3wasteland.com/index.php?topic=1099.0

**Comment by Beefaloaf** [comment]
update implemented. awaiting testing.

**Comment by l3v1ath3n** [comment]
awesome. i will let ya know! thanks beef
