### ISSUE TITLE
Night time server reset notice error

### ISSUE THREAD

**Issue by Dredhawk** [Beefaloaf/NANA_Wasteland.Altis#19]
The server states its goin to reset at 1:00 a.m. eastern, but doesn't actually reset until an hour later at 2:00a.m. eastern.

**Comment by Beefaloaf** [comment]
:rotating_light:
Made some changes to the restarting of the server.
The server now restarts at the following eastern times.
1, 5, and 9     AM and PM

I'm pretty sure they restart warnings in chat are not working anymore, and if they are, they're offset + or - an hour.  Please keep an eye out for it and let me know what time it happens, and how many hours off from an actual restart it is (if you happen to be on for that to happen)

Thanks!

**Comment by Beefaloaf** [comment]
ViLayer has an issue with our control panel link to our server.  Waiting for them to fix.  RCON scheduled events are done through the control panel.
