### ISSUE TITLE
Thermal sights for vehicle weapons

### ISSUE THREAD

**Issue by Dredhawk** [Beefaloaf/NANA_Wasteland.Altis#22]
most vehicles are supposed to have thermals but our server doesn't allow it, do we like this or do we want to change it?

**Comment by Cowasaur** [comment]
I would like it. Especially since the launchers have it. Blackfoot and kajman should almost certainly have it.

**Comment by l3v1ath3n** [comment]
id say ideally the top end ones should have maybe 3 of them. Not sure how that works in config.

**Comment by Beefaloaf** [comment]
Vehicle thermals activated, currently a blanket boolean switch.
See how this goes, in the future i might code some 'per vehicle' checking if needed.
