### ISSUE TITLE
unowned vehicles disappearing (during use)

### ISSUE THREAD

**Issue by l3v1ath3n** [Beefaloaf/NANA_Wasteland.Altis#25]
a truck, non purchased full of gear with a guy using inventory disappeared. seen this a couple times. may be server just repopulating spawn locations but i wanted to be sure it was discussed

**Comment by Beefaloaf** [comment]
Not a mission vehicle by chance?

**Comment by l3v1ath3n** [comment]
indeed they werent, i didnt realize they would disappear while being interacted with. driving down the road... POOF lol.
