### ISSUE TITLE
Earplugs in List 

### ISSUE THREAD

**Issue by l3v1ath3n** [Beefaloaf/NANA_Wasteland.Altis#32]
can we make that show up at the bottom of the scroll list?

**Comment by l3v1ath3n** [comment]
also perhaps vehicle info. Things that aren't detrimental. bottom of list?

**Comment by Beefaloaf** [comment]
Earplugs and VehicleInfo moved to the bottom.  Verified the earplugs, haven't verified the VehicleInfo yet.
