### ISSUE TITLE
Specialized load-outs for classes

### ISSUE THREAD

**Issue by Beefaloaf** [Beefaloaf/NANA_Wasteland.Altis#5]
Dear Mr Beefaloaf, could you make it so that individual classes have unique traits?  They all seem to blend together in their default state.

**Comment by Beefaloaf** [comment]
Progress made.
Only snipers can use sniper rifles, and only the diver can grab the watergun.

Eventually, i'll script some code that checks whether you are near a vendor while obtaining an illegal gun for your class.  If true, you will be refunded.  Currently, you are ripped off if you purchase one.

**Comment by l3v1ath3n** [comment]
This is awesome... I think we should remove the diver class altogether. Make everyone able to pick up the rifle and do the mission. The water missions are such a pain, not many people do them as is.. Maybe we make them worth more ? Thoughts?

**Comment by Beefaloaf** [comment]
I like them, they were so easy to do if you were prepared...    I think the diver needs more...    just not sure what yet.  I know Wolf eats them up.

**Comment by l3v1ath3n** [comment]
They are indeed if you are prepared..but a player will not log out to change their class to go complete a diving mission. know what I mean?

**Comment by Beefaloaf** [comment]
I'll be adding new classes eventually.  Diver will not be one of them.
